steps:
- name: gcr.io/cloud-builders/git
  args:
    - submodule
    - update
    - '--init'
    - '--recursive'
    - '--remote'
- name: maven:3.3-jdk-8
  entrypoint: mvn
  args:
    - test
  dir: $_FOLDER
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
substitutions:
  _FOLDER: neo4j-plugins
